[package]
name = "graphicsmagick"
version = "0.1.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
license = "MIT"
description = "GraphicsMagick binding for Rust."
readme = "README.md"
repository = "https://github.com/jmjoy/graphicsmagick-rs"
keywords = ["image", "binding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
static = ["graphicsmagick-sys/static"]

[dependencies]
graphicsmagick-sys = { version = "0.1.0", path = "../graphicsmagick-sys" }
libc = "0.2.68"
thiserror = "1.0.14"

[dev-dependencies]
anyhow = "1.0.28"
env_logger = "0.7.1"
