[package]
name = "graphicsmagick"
version = "0.2.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
license = "MIT"
description = "GraphicsMagick binding for Rust."
readme = "README.md"
repository = "https://github.com/jmjoy/graphicsmagick-rs"
keywords = ["image", "magick", "gmagick", "imagemagick", "imagick"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
static = ["graphicsmagick-sys/static"]

[dependencies]
graphicsmagick-sys = { version = "0.1.1", path = "../graphicsmagick-sys" }
libc = "0.2.68"
thiserror = "1.0.14"

[dev-dependencies]
anyhow = "1.0.28"
env_logger = "0.7.1"

[build-dependencies]
anyhow = "1.0.28"
graphicsmagick-sys = { version = "0.1.1", path = "../graphicsmagick-sys" }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]
