[package]
name = "graphicsmagick"
version = "0.1.0"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
license = "MIT"
description = "GraphicsMagick binding for Rust."
readme = "README.md"
repository = "https://github.com/jmjoy/graphicsmagick-rs"
keywords = ["image", "binding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#encoding_rs = "0.8.22"
graphicsmagick-sys = { version = "0.1.0", path = "../graphicsmagick-sys" }
libc = "0.2.68"
#libc = "0.2.68"
# once_cell = "1.3.1"
thiserror = "1.0.14"

[dev-dependencies]
anyhow = "1.0.28"
env_logger = "0.7.1"
